module.exports = {
  LOGIN: {
    INIT_LOADING: 'INIT_LOADING',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_CLEAR: 'LOGIN_CLEAR'
  },
  VERIFY_OTP: {
    REQUEST: 'VERIFY_OTP_REQUEST',
    SUCCESS: 'VERIFY_OTP_SUCCESS',
    FAILURE: 'VERIFY_OTP_FAILURE',
    CLEAR: 'VERIFY_OTP_CLEAR'
  },
  VERIFY_NEW_USER: {
    REQUEST: 'VERIFY_NEW_USER_REQUEST',
    SUCCESS: 'VERIFY_NEW_USER_SUCCESS',
    FAILURE: 'VERIFY_NEW_USER_FAILURE',
    CLEAR: 'VERIFY_NEW_USER_CLEAR'
  },
  CONFIG: {
    CONFIG_REQUEST: 'CONFIG_REQUEST',
    CONFIG_SUCCESS: 'CONFIG_SUCCESS',
    CONFIG_FAILURE: 'CONFIG_FAILURE',
    CONFIG_CLEAR: 'CONFIG_CLEAR'
  },
  CONFIG_AREA: {
    CONFIG_AREA_REQUEST: 'CONFIG_AREA_REQUEST',
    CONFIG_AREA_SUCCESS: 'CONFIG_AREA_SUCCESS',
    CONFIG_AREA_FAILURE: 'CONFIG_AREA_FAILURE',
    CONFIG_AREA_CLEAR: 'CONFIG_AREA_CLEAR'
  },
  HOME: {
    SUCCESS: 'HOME_SUCCESS',
    REQUEST: 'HOME_REQUEST',
    FAILURE: 'HOME_FAILURE',
    CLEAR: 'HOME_CLEAR',
    SEARCH: 'HOME_SEARCH',
    SELECTED_COOK: 'SELECTED_COOK'
  },
  NEW_USER_CHECK: {
    SUCCESS: 'IS_NEW_USER_SUCCESS',
    REQUEST: 'IS_NEW_USER_REQUEST',
    FAILURE: 'IS_NEW_USER_FAILURE',
    CLEAR: 'IS_NEW_USER_CLEAR'
  },
  CHECK_SOCIAL_USER: {
    SUCCESS: 'SOCIAL_USER_SUCCESS',
    REQUEST: 'SOCIAL_USER_REQUEST',
    FAILURE: 'SOCIAL_USER_FAILURE',
    CLEAR: 'SOCIAL_USER_CLEAR'
  },
  BOOKING: {
    SUCCESS: 'BOOKING_SUCCESS',
    REQUEST: 'BOOKING_REQUEST',
    FAILURE: 'BOOKING_FAILURE',
    CLEAR: 'BOOKING_CLEAR',
    BOOKING_SELECTED_COOK_DATA: 'BOOKING_SELECTED_COOK_DATA',
    BOOKING_SELECTED_COOK_DATA_CLEAR: 'BOOKING_SELECTED_COOK_DATA_CLEAR'
  },
  SUMMARY: {
    SUCCESS: 'SUMMARY_SUCCESS',
    REQUEST: 'SUMMARY_REQUEST',
    FAILURE: 'SUMMARY_FAILURE',
    CLEAR: 'SUMMARY_CLEAR',
    SUMMARY_STATE_DATA: 'SUMMARY_STATE_DATA',
    CLEAR_SUMMARY_VALUE: 'CLEAR_SUMMARY_VALUE',
    BOOKING_SUMMARY_REQUEST: 'BOOKING_SUMMARY_REQUEST',
    RECEIVED: 'SUMMARY_RECEIVED',
    CLEAR_ADDON_SUMMARY_VALUE: 'CLEAR_ADDON_SUMMARY_VALUE',
    ADDONREQUEST: 'ADDONREQUEST',
    ADDONSUCCESS: 'ADDONSUCCESS',
    ADDONFAILURE: 'ADDONFAILURE'
  },
  CHECKOUT: {
    SUCCESS: 'CHECKOUT_SUCCESS',
    REQUEST: 'CHECKOUT_REQUEST',
    FAILURE: 'CHECKOUT_FAILURE',
    CLEAR: 'CHECKOUT_CLEAR'
  },
  WELCOMECOOK: {
    SUCCESS: 'WELCOMECOOK_SUCCESS',
    REQUEST: 'WELCOMECOOK_REQUEST',
    FAILURE: 'WELCOMECOOK_FAILURE',
    CLEAR: 'WELCOMECOOK_CLEAR',
    NOTIFICATIONCLEAR: 'NOTIFICATIONCLEAR'
  },
  COOKACCEPT: {
    SUCCESS: 'COOKACCEPT_SUCCESS',
    REQUEST: 'COOKACCEPT_REQUEST',
    FAILURE: 'COOKACCEPT_FAILURE',
    CLEAR: 'COOKACCEPT_CLEAR'
  },
  COOKREJECTORDER: {
    SUCCESS: 'COOKREJECTORDER_SUCCESS',
    REQUEST: 'COOKREJECTORDER_REQUEST',
    FAILURE: 'COOKREJECTORDER_FAILURE',
    CLEAR: 'COOKREJECTORDER_CLEAR'
  },
  USERBOOKING: {
    SUCCESS: 'USERBOOKING_SUCCESS',
    REQUEST: 'USERBOOKING_REQUEST',
    FAILURE: 'USERBOOKING_FAILURE',
    CLEAR: 'USERBOOKING_CLEAR'
  },
  USERPASTBOOKING: {
    SUCCESS: 'USERPASTBOOKING_SUCCESS',
    REQUEST: 'USERPASTBOOKING_REQUEST',
    FAILURE: 'USERPASTBOOKING_FAILURE',
    CLEAR: 'USERPASTBOOKING_CLEAR'
  },
  ONLINE: {
    SUCCESS: 'ONLINE_SUCCESS',
    REQUEST: 'ONLINE_REQUEST',
    FAILURE: 'ONLINE_FAILURE',
    CLEAR: 'ONLINE_CLEAR'
  },
  GETPROFILE: {
    SUCCESS: 'GET_PROFILE_SUCCESS',
    REQUEST: 'GET_PROFILE_REQUEST',
    FAILURE: 'GET_PROFILE_FAILURE',
    CLEAR: 'GET_PROFILE_CLEAR',
    LOADING: 'LOADING'
  },
  GETCUISINES: {
    SUCCESS: 'CUISINE_SUCCESS',
    REQUEST: 'CUISINE_REQUEST',
    FAILURE: 'CUISINE_FAILURE',
    CLEAR: 'CUISINE_CLEAR'
  },
  GETFOODTYPES: {
    SUCCESS: 'FOODTYPE_SUCCESS',
    REQUEST: 'FOODTYPE_REQUEST',
    FAILURE: 'FOODTYPE_FAILURE',
    CLEAR: 'FOODTYPE_CLEAR'
  },
  COOKCANCEL: {
    SUCCESS: 'COOKCANCEL_SUCCESS',
    REQUEST: 'COOKCANCEL_REQUEST',
    FAILURE: 'COOKCANCEL_FAILURE',
    CLEAR: 'COOKCANCEL_CLEAR'
  },
  PROFILEUPDATE: {
    SUCCESS: 'PROFILEUPDATE_SUCCESS',
    REQUEST: 'PROFILEUPDATE_REQUEST',
    FAILURE: 'PROFILEUPDATE_FAILURE',
    CLEAR: 'PROFILEUPDATE_CLEAR'
  },
  DOCUMENT_UPLOAD: {
    SUCCESS: 'DOCUMENT_UPLOAD_SUCCESS',
    REQUEST: 'DOCUMENT_UPLOAD_REQUEST',
    FAILURE: 'DOCUMENT_UPLOAD_FAILURE',
    CLEAR: 'CLEAR'
  },
  OTHER_DOCUMENT_UPLOAD: {
    SUCCESS: 'OTHER_DOCUMENT_UPLOAD_SUCCESS',
    REQUEST: 'OTHER_DOCUMENT_UPLOAD_REQUEST',
    FAILURE: 'OTHER_DOCUMENT_UPLOAD_FAILURE',
    CLEAR: 'CLEAR'
  },
  IMAGE_UPLOAD: {
    SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
    REQUEST: 'IMAGE_UPLOAD_REQUEST',
    FAILURE: 'IMAGE_UPLOAD_FAILURE',
    CLEAR: 'CLEAR'
  },
  RATING: {
    SUCCESS: 'RATING_SUCCESS',
    FAILURE: 'RATING_FAILURE',
    REQUEST: 'RATING_REQUEST',
    CLEAR: 'RATING_CLEAR'
  },
  PENDING_REVIEW: {
    SUCCESS: 'PENDING_REVIEW_SUCCESS',
    FAILURE: 'PENDING_REVIEW_FAILURE',
    REQUEST: 'PENDING_REVIEW_REQUEST',
    CLEAR: 'PENDING_REVIEW_CLEAR'
  },
  QUICK_BOOK: {
    SUCCESS: 'QUICK_BOOK_SUCCESS',
    FAILURE: 'QUICK_BOOK_FAILURE',
    REQUEST: 'QUICK_BOOK_REQUEST',
    CLEAR: 'QUICK_BOOK_CLEAR'
  },
  TRANSCATION_LIST: {
    SUCCESS: 'TRANSCATION_LIST_SUCCESS',
    FAILURE: 'TRANSCATION_LIST_FAILURE',
    REQUEST: 'TRANSCATION_LIST_REQUEST',
    CLEAR: 'TRANSCATION_LIST_CLEAR'
  },
  UPDATEWALLET: {
    SUCCESS: 'UPDATEWALLET_SUCCESS',
    FAILURE: 'UPDATEWALLET_FAILURE',
    REQUEST: 'UPDATEWALLET_REQUEST',
    CLEAR: 'UPDATEWALLET_CLEAR'
  },
  TODAYEARNING: {
    SUCCESS: 'TODAYEARNING_SUCCESS',
    FAILURE: 'TODAYEARNING_FAILURE',
    REQUEST: 'TODAYEARNING_REQUEST',
    CLEAR: 'TODAYEARNING_CLEAR'
  },
  WEEKLYEARNING: {
    SUCCESS: 'WEEKLYEARNING_SUCCESS',
    FAILURE: 'WEEKLYEARNING_FAILURE',
    REQUEST: 'WEEKLYEARNING_REQUEST',
    CLEAR: 'WEEKLYEARNING_CLEAR'
  },
  WITHDRAW: {
    SUCCESS: 'WITHDRAW_SUCCESS',
    FAILURE: 'WITHDRAW_FAILURE',
    REQUEST: 'WITHDRAW_REQUEST',
    CLEAR: 'WITHDRAW_CLEAR'
  },
  WITHDRAWLIST: {
    SUCCESS: 'WITHDRAWLISTSUCCESS',
    FAILURE: 'WITHDRAWLIST_FAILURE',
    REQUEST: 'WITHDRAWLIST_REQUEST',
    CLEAR: 'WITHDRAWLIST_CLEAR'
  },
  GETMAPADDRESS: {
    SUCCESS: 'GETMAPADDRESS_SUCCESS',
    REQUEST: 'GETMAPADDRESS_REQUEST',
    FAILURE: 'GETMAPADDRESS_FAILURE',
    CLEAR: 'GETMAPADDRESS_CLEAR'
  },
  ADDADDRESS: {
    SUCCESS: 'ADDADDRESS_SUCCESS',
    REQUEST: 'ADDADDRESS_REQUEST',
    FAILURE: 'ADDADDRESS_FAILURE',
    CLEAR: 'ADDADDRESS_CLEAR'
  },
  ADDRESSLIST: {
    SUCCESS: 'ADDRESSLIST_SUCCESS',
    REQUEST: 'ADDRESSLIST_REQUEST',
    FAILURE: 'ADDRESSLIST_FAILURE',
    CLEAR: 'ADDRESSLIST_CLEAR'
  },
  USERDEFAULTADDRESS: {
    SUCCESS: 'USERDEFAULTADDRESS_SUCCESS',
    REQUEST: 'USERDEFAULTADDRESS_REQUEST',
    FAILURE: 'USERDEFAULTADDRESS_FAILURE',
    CLEAR: 'USERDEFAULTADDRESS_CLEAR'
  },
  SETUSERDEFAULTADDRESS: {
    SUCCESS: 'SETUSERDEFAULTADDRESS_SUCCESS',
    REQUEST: 'SETUSERDEFAULTADDRESS_REQUEST',
    FAILURE: 'SETUSERDEFAULTADDRESS_FAILURE',
    CLEAR: 'SETUSERDEFAULTADDRESS_CLEAR'
  },
  GETBYADDRESS: {
    SUCCESS: 'GETBYADDRESS_SUCCESS',
    REQUEST: 'GETBYADDRESS_REQUEST',
    FAILURE: 'GETBYADDRESS_FAILURE',
    CLEAR: 'GETBYADDRESS_CLEAR'
  },
  UPDATEADDRESS: {
    SUCCESS: 'UPDATEADDRESS_SUCCESS',
    REQUEST: 'UPDATEADDRESS_REQUEST',
    FAILURE: 'UPDATEADDRESS_FAILURE',
    CLEAR: 'UPDATEADDRESS_CLEAR'
  },
  DELETEADDRESS: {
    SUCCESS: 'DELETEADDRESS_SUCCESS',
    REQUEST: 'DELETEADDRESS_REQUEST',
    FAILURE: 'DELETEADDRESS_FAILURE',
    CLEAR: 'DELETEADDRESS_CLEAR'
  },
  GETMEALTYPE: {
    SUCCESS: 'MEALTYPE_SUCCESS',
    REQUEST: 'MEALTYPE_REQUEST',
    FAILURE: 'MEALTYPE_FAILURE',
    CLEAR: 'MEALTYPE_CLEAR'
  },
  UPDATE_ORDER: {
    SUCCESS: 'UPDATE_ORDER_SUCCESS',
    REQUEST: 'UPDATE_ORDER_REQUEST',
    FAILURE: 'UPDATE_ORDER_FAILURE',
    CLEAR: 'UPDATE_ORDER_CLEAR'
  },
  UPDATE_SUBORDER: {
    SUCCESS: 'UPDATE_SUBORDER_SUCCESS',
    REQUEST: 'UPDATE_SUBORDER_REQUEST',
    FAILURE: 'UPDATE_SUBORDER_FAILURE',
    CLEAR: 'UPDATE_SUBORDER_CLEAR'
  },
  COUPON: {
    SUCCESS: 'COUPON_SUCCESS',
    REQUEST: 'COUPON_REQUEST',
    FAILURE: 'COUPON_FAILURE',
    CLEAR: 'COUPON_CLEAR'
  },
  GET_ORDERS: {
    REQUEST: 'GET_ORDERS_REQUEST',
    FAILURE: 'GET_ORDERS_FAILURE',
    SUCCESS: 'GET_ORDERS_SUCCESS',
    CLEAR: 'GET_ORDERS_CLEAR'
  },
  CONTACTUS: {
    SUCCESS: 'CONTACTUS_SUCCESS',
    REQUEST: 'CONTACTUS_REQUEST',
    FAILURE: 'CONTACTUS_FAILURE',
    CLEAR: 'CONTACTUS_CLEAR'
  },
  MANUALNOTIFICATION: {
    SUCCESS: 'MANUALNOTIFICATION_SUCCESS',
    REQUEST: 'MANUALNOTIFICATION_REQUEST',
    FAILURE: 'MANUALNOTIFICATION_FAILURE',
    CLEAR: 'MANUALNOTIFICATION_CLEAR'
  },
  INITIALREQUEST: 'INITIALREQUEST',
  CREATERAZORORDER: {
    SUCCESS: 'CREATERAZORORDER_SUCCESS',
    REQUEST: 'CREATERAZORORDER_REQUEST',
    FAILURE: 'CREATERAZORORDER_FAILURE',
    CLEAR: 'CREATERAZORORDER_CLEAR'
  },
  RESCHEDULE: {
    SUCCESS: 'RESCHEDULE_SUCCESS',
    REQUEST: 'RESCHEDULE_REQUEST',
    FAILURE: 'RESCHEDULE_FAILURE',
    CLEAR: 'RESCHEDULE_CLEAR'
  },
  RESCHEDULEORDER: {
    SUCCESS: 'RESCHEDULEORDER_SUCCESS',
    REQUEST: 'RESCHEDULEORDER_REQUEST',
    FAILURE: 'RESCHEDULEORDER_FAILURE',
    CLEAR: 'RESCHEDULEORDER_CLEAR'
  },
  COOKACCEPTRESCHEDULE: {
    SUCCESS: 'COOKACCEPTRESCHEDULE_SUCCESS',
    REQUEST: 'COOKACCEPTRESCHEDULE_REQUEST',
    FAILURE: 'COOKACCEPTRESCHEDULE_FAILURE',
    CLEAR: 'COOKACCEPTRESCHEDULE_CLEAR'
  },
  COOKREJECTRESCHEDULE: {
    SUCCESS: 'COOKREJECTRESCHEDULE_SUCCESS',
    REQUEST: 'COOKREJECTRESCHEDULE_REQUEST',
    FAILURE: 'COOKREJECTRESCHEDULE_FAILURE',
    CLEAR: 'COOKREJECTRESCHEDULE_CLEAR'
  },
  CURRENTTIME: {
    CURRENTTIME_REQUEST: 'CURRENTTIME_REQUEST',
    CURRENTTIME_SUCCESS: 'CURRENTTIME_SUCCESS',
    CURRENTTIME_FAILURE: 'CURRENTTIME_FAILURE',
    CURRENTTIME_CLEAR: 'CURRENTTIME_CLEAR'
  },
  COOKSTARTORDER: {
    REQUEST: 'COOKSTARTORDER_REQUEST',
    SUCCESS: 'COOKSTARTORDER_SUCCESS',
    FAILURE: 'COOKSTARTORDER_FAILURE',
    CLEAR: 'COOKSTARTORDER_CLEAR'
  },
  COVID_ALERT: {
    REQUEST: 'COVID_ALERT_REQUEST',
    SUCCESS: 'COVID_ALERT_SUCCESS',
    FAILURE: 'COVID_ALERT_FAILURE',
    CLEAR: 'COVID_ALERT_CLEAR'
  },
  GUEST_LOGIN: {
    SUCCESS: 'GUEST_LOGIN_SUCCESS',
    REQUEST: 'GUEST_LOGIN_REQUEST',
    FAILURE: 'GUEST_LOGIN_FAILURE',
    CLEAR: 'GUEST_LOGIN_CLEAR'
  },
  CHECK_GUEST_EXIST: {
    SUCCESS: 'CHECK_GUEST_EXIST_SUCCESS',
    REQUEST: 'CHECK_GUEST_EXIST_REQUEST',
    FAILURE: 'CHECK_GUEST_EXIST_FAILURE',
    CLEAR: 'CHECK_GUEST_EXIST_CLEAR'
  }
}
